name: fakenews
on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubutun-latest
    steps:
    
    - name: 获取最新代码
      uses: actions/checkout@master

    - name: 设置JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

    - name: 项目打包
        run: mvn -B package
